# Configuration for pleonex website
baseurl = "/"
title = "Pleotonic Engineering"
copyright = "&copy; 2018 Benito Palacios Sánchez"

theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# No Disqus (comment system) or Google Analytics.
disqusShortname = ""
googleAnalytics = ""

# Only English :)
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

# No git info needed
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
[blackfriday]
  hrefTargetBlank = true  # Always external links in new tab!
  fractions = true  # Convert fractions
  smartypants = true  # Convert quotes, dashes, ...

[params]
  # My details.
  name = "Benito Palacios (pleonex)"
  role = "Software Engineer"

  # Organizations/Affiliations.
  organizations = [
    { name = "Real-Time Innovation (RTI)", url = "http://www.rti.com" },
    { name = "TraduSquare", url = "https://tradusquare.es/" }
  ]

  # Use a custom photo
  gravatar = false
  avatar = "portrait.jpg"

  # Contact info
  email = "benito356@gmail.com"
  address = "Granada, Spain"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = "pleonex"
  keybase = ""

  # No discussion
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # No map thanks
  map = 0
  map_api_key = ""
  latitude = ""
  longitude = ""
  zoom = 15

  # Color theme.
  color_theme = "pleodark"

  # Font style.
  font = "default"

  # Info for search engines and social sharing
  description = ""  # Take the 
  sharing_img = "portrait.jpg"
  twitter = "pleonex"

  # I prefer the title instead of a logo
  logo = ""

  # Date and time format
  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"

  # Show estimated reading time for posts?
  reading_time = true

  # No comments enabled
  comment_count = false

  # Display section pager for posts?
  section_pager = false

  # Enable global LaTeX math rendering?
  math = false

  # Highlight.js options
  highlight = true
  highlight_languages = ["cs"]  # C#!
  highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = true

  # Link custom CSS and JS assets
  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Dissertation / Thesis',  # 1
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

    # Talk list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    talk_format = 2

  # Social Networking
  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "mailto:benito356@gmail.com"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/pleonex"

  [[params.social]]
    icon = "cv"
    icon_pack = "ai"
    link = "files/CV_BenitoPalacios.pdf"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    link = "//www.linkedin.com/in/pleonex"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "//twitter.com/pleonex"


# Navigation Links
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

  [[menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 3

# Hide until first post
# [[menu.main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 4

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 5
  
[[menu.main]]
  name = "Translations"
  url = "#translations"
  weight = 6

[[menu.main]]
  name = "CV"
  url = "files/CV_BenitoPalacios.pdf"
  weight = 7

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 8

  # Search.
  [params.search]
    # Search provider:
    #   0: No search engine
    #   1: Built-in (Fuse)
    #   2: Algolia (https://www.algolia.com)
  engine = 0

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
[Languages.en]
  languageCode = "en-us"
