baseurl = "pleonex.github.io/"
title = "Pleotonic Engineering"
copyright = "&copy; 2017 Benito Palacios Sánchez"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `coffee`, or `dark`.
  color_theme = "default"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Your details.
  name = "Benito Palacios"
  role = "Software Engineer"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [
    { name = "Real-Time Innovation", url = "http://www.rti.com" },
    { name = "GradienWords", url = "http://gradienwords.es" }
  ]

  gravatar = false
  avatar = "portrait.jpg"
  email = "benito356@gmail.com"
  address = "Granada, Spain"
  office_hours = ""
  phone = ""
  skype = ""
  telegram = "pleonex"
  keybase = ""

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Diplay a logo in navigation bar rather than title (optional).
  logo = ""

  # Enable/disable map in Contact widget.
  map = 0
  map_api_key = ""
  latitude = "37.4275"
  longitude = "-122.1697"
  zoom = 15

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display section pager for posts?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   For the list of supported languages and styles, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://sourcethemes.com/academic/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["cs"]
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

  # Social Networking
  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:benito356@gmail.com"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/pleonex"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/pleonex"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/pleonex"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 5

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
[Languages.en]
  languageCode = "en-us"
